trigger:
- main

pool:
  vmImage: ubuntu-22.04

variables:
  tag: '$(Build.BuildId)'
  nexusRegistry: 'nexus.x100group.com'
  imagePath: 'finance/x100group.jetti-server'

stages:

- stage: Build
  displayName: 'Build and publish image'

  jobs:

  - job: Build
    displayName: 'Build'

    steps:

    - checkout: self

    - script: |
        set -euo pipefail

        echo "$NEXUS_PASSWORD" \
          | docker login "$(nexusRegistry)" \
              --username "$NEXUS_USER" \
              --password-stdin

      env:
        NEXUS_USER: $(NEXUS_USER)
        NEXUS_PASSWORD: $(NEXUS_PASSWORD)

      displayName: 'Docker login to Nexus'


    - script: |
        set -euo pipefail

        IMAGE="$(nexusRegistry)/$(imagePath):$(tag)"

        echo "Building:"
        echo "$IMAGE"

        docker build \
          --label "org.opencontainers.image.revision=$(Build.SourceVersion)" \
          --label "org.opencontainers.image.version=$(tag)" \
          -t "$IMAGE" \
          .

      displayName: 'Docker build'


    # - script: |
    #     set -euo pipefail

    #     IMAGE="$(nexusRegistry)/$(imagePath):$(tag)"

    #     echo "Publishing:"
    #     echo "$IMAGE"

    #     docker push "$IMAGE"

    #     echo
    #     echo "Published successfully"

    #   displayName: 'Docker push to Nexus'

    - script: |
        set -euo pipefail
        # 1. Авторизация на едином эндпоинте
        docker login $(nexusRegistry) -u $(NEXUS_USER) -p $(NEXUS_PASSWORD)
        # 2. Сборка и тегирование (каталог finance создастся в Nexus автоматически)
        IMAGE="$(nexusRegistry)/$(imagePath):$(tag)"
        docker build -t "$IMAGE" .
        # 3. Публикация образа
        echo "Publishing image: $IMAGE"
        docker push "$IMAGE"
        echo "Published successfully"
      displayName: 'Docker push to Nexus'


    - script: |
        docker logout "$(nexusRegistry)" || true

      displayName: 'Docker logout'
      condition: always()