#az aks get-credentials --resource-group x100-kube --name jetti-apps
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: smaz
  labels:
    app: smaz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smaz
        tier: web
    spec:
      containers:
        - name: jetti
          image: jetticr.azurecr.io/jetti-api:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_PORT
              value: "1433"
            - name: DB_HOST
              value: jetti-sm.database.windows.net
            - name: DB_NAME
              value: sm
            - name: DB_USER
              value: jetti
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-db-credentials
                  key: password
            - name: DB_TASK_USER
              value: yuralex
            - name: DB_TASK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-db-credentials
                  key: password
            - name: DB_ACCOUNTS_HOST
              value: sql.jetti-app.com
            - name: DB_ACCOUNTS_NAME
              value: accounts
            - name: DB_ACCOUNTS_USER
              valueFrom:
                secretKeyRef:
                  name: account-db-credentials
                  key: username
            - name: DB_ACCOUNTS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-db-credentials
                  key: password
            - name: REDIS_DB_HOST
              value: redis
            - name: JTW_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: JTW_KEY
            - name: REFRESH_ID
              value: "0001"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: smaz
  labels:
    app: smaz
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: smaz
  ports:
  - port: 8080
    targetPort: 8080